#!/bin/bash

export CUDA_HOME=/usr/local/cuda


cmake \
  -DCLANG_FORMAT_BIN=/usr/bin/clang-format \
  -DCLANG_TIDY_BIN=/usr/bin/clang-tidy \
  -DARROW_JEMALLOC=ON \
  -DARROW_COMPUTE=ON \
  -DARROW_CSV=ON \
  -DARROW_CUDA=ON \
  -DARROW_DATASET=ON \
  -DARROW_FILESYSTEM=ON \
  -DARROW_JSON=ON \
  -DARROW_PARQUET=ON \
  -DPARQUET_BUILD_EXECUTABLES=ON \
  -DPARQUET_BUILD_EXAMPLES=ON \
  -DARROW_WITH_BZ2=ON \
  -DARROW_WITH_ZLIB=ON \
  -DARROW_WITH_LZ4=ON \
  -DARROW_WITH_SNAPPY=ON \
  -DARROW_WITH_ZSTD=ON \
  -DARROW_BUILD_EXAMPLES=ON \
  -DARROW_BUILD_INTEGRATION=ON \
  -DARROW_BUILD_UTILITIES=ON \
  ..
